package com.example.demo.exception;


public enum ErrorMessage {
	WALLET_NOT_FOUND,
    INSUFFICIENT_BALANCE,
    INVALID_REQUEST,
    INTERNAL_SERVER_ERROR,
    EMAIL_OR_PHONE_NUMBER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    INACTIVE_BANK_ACCOUNT,
    NOT_VERIFIED_BANK_ACCOUNT,
    INVALID_BANK_ACCOUNT,
    SET_MPIN_BEFORE_WITHDRAWAL,
    INVALID_MPIN,
    RECEIVER_NOT_FOUND,
    SELF_TRANSFER_NOT_ALLOWED,
    SENDER_WALLET_NOT_FOUND,
    RECEIVER_WALLET_NOT_FOUND,
    INVALID_FILE_TYPE,
    FILE_SIZE_MUST_BE_LESS_THAN_2MB,
    FILE_IS_REQUIRED,
    KYC_ALREADY_SUBMITTED,
    KYC_ALREADY_APPROVED,
    FAIL_TO_UPLOAD_KYC_DOCUMENT,
    KYC_NOT_FOUND,
    KYC_IS_NOT_PENDING,
    REJECTING_WITHOUT_GIVING_REASON,
    KYC_NOT_APPROVED,
    MISSING_IDEMPOTENCY_KEY,
    BANK_ACCOUNT_NOT_FOUND,
    ACCOUNT_OWNERSHIP_MISMATCH,
    AMOUNT_LESS_THAN_100,
    PRIMARY_BANK_ACCOUNT_NOT_FOUND,
    SPLIT_NOT_FOUND,
    YOU_ARE_NOT_A_PART_OF_THIS_SPLIT,
    MEMBERS_ARE_REQUIRED,
    MEMBERS_ARE_ONLY_ALLOWED_NO_MERCHANTS,
    IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_REQUEST_BODY,
    // Split
    SPLIT_AMOUNT_INVALID,
    SPLIT_AMOUNT_TOO_MANY_DECIMALS,
    SPLIT_EQUAL_NOT_DIVISIBLE,
    SPLIT_CUSTOM_SHARES_REQUIRED,
    SPLIT_CUSTOM_KEYS_MISMATCH,
    SPLIT_CUSTOM_SUM_MISMATCH,
    SPLIT_CUSTOM_SHARE_INVALID,
    SPLIT_CUSTOM_SHARE_NON_POSITIVE,

    // Pay
    SPLIT_ALREADY_PAID
}

