/**
 * The best practise is to use hybrid strategy like the combination of pages and components, some times 
 * pages and sometimes components, like that for the labels.config thing.
 */
export const LABELS = {
  commonComponents: {
    addBankAccountModal: {
      title: "Link Bank Account",
      description: "Add your banking details to enable seamless fund transfers and withdrawals.",
      bankName: "Bank Name",
      bankNamePlaceholder: "e.g. State Bank of India",
      accountNumber: "Account Number",
      accountNumberPlaceholder: "0000 0000 0000",
      ifscCode: "IFSC Code",
      ifscPlaceholder: "SBIN0001234",
      linkingAccount: "Linking Account...",
      linkBankAccount: "Link Bank Account",
      encryptedConnection: "End-to-end encrypted connection",
    },
    bankAccountsList: {
      title: "Linked Bank Accounts",
      addBank: "Add Bank",
      noAccounts: "No bank accounts linked yet.",
      linkFirstAccount: "Link your first account",
      primary: "PRIMARY",
      balance: "Balance",
      setDefaultForSettlements: "Set as default for settlements",
    },
    bankSelector: {
      defaultLabel: "Select Bank Account",
      placeholder: "Choose an account",
    },
    header: {
      brand: "SwiftPay",
      adminConsole: "Admin Console",
      merchantPro: "Merchant Pro",
      digitalWallet: "Digital Wallet",
      navOverview: "Overview",
      navHistory: "History",
      navSettlements: "Settlements",
      navMyActivity: "My Activity",
      completeSetup: "Complete Setup",
      kycPrefix: "KYC:",
      kycPending: "PENDING",
      myDashboard: "My Dashboard",
      securityCenter: "Security Center",
      signOut: "Sign Out",
      login: "Login",
      getStarted: "Get Started",
      customerAccount: "Customer Account",
      customerAccountSub: "For personal payments",
      merchantAccount: "Merchant Account",
      merchantAccountSub: "For business & settlements",
    },
    kycUpload: {
      documentsSubmitted: "Documents submitted!",
      uploadFailed: "Upload failed",
      identityVerified: "Identity Verified",
      selectIdentityProof: "Select Identity Proof",
      identityProofHint: "Aadhar, PAN or Passport (PDF/JPG)",
      uploadAndVerify: "Upload & Verify",
    },
    paymentModeSelector: {
      label: "Select Payment Mode",
      upi: "UPI",
      netBanking: "Net Banking",
      debitCard: "Debit Card",
      walletBalance: "Wallet Balance",
    },
    securityModal: {
      title: "Security Checklist",
      verified: "Verified",
      kycDescription: "Verify your identity to increase limits.",
      mpinDescription: "Secure your wallet for transactions.",
      identityVerification: "Identity Verification",
      nextMpin: "Next: MPIN",
      kycUnderReview: "KYC Under Review",
      kycPendingDetail: "You've already submitted your documents. We'll notify you once approved.",
      verificationRejected: "Verification Rejected",
      rejectionReasonPrefix: "Reason:",
      defaultRejectionReason: "Invalid document",
      resetMpin: "Reset Transaction MPIN",
      setMpin: "Set Transaction MPIN",
      mpinAlreadySet: "You already have an MPIN set. Updating it will replace the old one.",
    },
    setMpinCard: {
      resetSuccess: "MPIN Reset Successfully",
      setSuccess: "MPIN Set Successfully",
      processFailed: "Process failed. Please try again.",
      newMpin: "New 4-Digit MPIN",
      confirmMpin: "Confirm MPIN",
      mpinPlaceholder: "\u2022\u2022\u2022\u2022",
      updateAndSecureWallet: "Update & Secure Wallet",
      setMpinAndSecureWallet: "Set MPIN & Secure Wallet",
    },
  },
  adminComponents: {
    highValueSummaryWidget: {
      title: "High Value Merchants",
      showingPrefix: "Showing",
      offsetPrefix: "Offset",
      loadingFailed: "Failed to load merchants summary.",
      noMerchants: "No merchants found.",
      colBusiness: "Business",
      colCode: "Code",
      colCategory: "Category",
      colHighTxns: "High Txns",
      colTotalAmount: "Total Amount",
      colDistinctPayers: "Distinct Payers",
      colAction: "Action",
      viewing: "Viewing",
      viewMore: "View More",
      prev: "Prev",
      next: "Next",
    },
    highValueTransactionsWidget: {
      title: "High Value Transactions",
      merchantPrefix: "Merchant #",
      close: "Close",
      loadingFailed: "Failed to load transactions.",
      noTransactions: "No high-value transactions found.",
      colTx: "TX",
      colPayer: "Payer",
      colAmount: "Amount",
      colStatus: "Status",
      colMode: "Mode",
      colType: "Type",
      colCreated: "Created",
      showingPrefix: "Showing",
      offsetPrefix: "Offset",
      prev: "Prev",
      next: "Next",
      statusSuccess: "SUCCESS",
      statusFailed: "FAILED",
      statusPending: "PENDING",
    },
    kycPreviewModal: {
      title: "Document Preview",
      inspectorTitle: "Document Inspector",
      iframeTitle: "KYC PDF",
      imageAlt: "KYC",
    },
    kycRejectModal: {
      title: "Reject Application",
      reasonLabel: "Reason for Rejection",
      reasonPlaceholder: "e.g., Documents are blurry or expired...",
      cancel: "Cancel",
      confirmRejection: "Confirm Rejection",
    },
    kycTable: {
      colIdentityInformation: "Identity Information",
      colVerificationAssets: "Verification Assets",
      colDecisionConsole: "Decision Console",
      uidPrefix: "UID:",
      auditDocument: "Audit Document",
      reject: "Reject",
      verifyUser: "Verify User",
    },
  },
  kycComponents: {
    pendingKycList: {
      loading: "Loading...",
      approve: "Approve",
      reject: "Reject",
      rejectReasonDefault: "Invalid Doc",
    },
    uploadKyc: {
      uploaded: "KYC uploaded",
      uploadButton: "Upload KYC",
    },
  },
  merchantComponents: {
    recentActivity: {
      tabPayments: "Payments",
      tabSettlements: "Settlements",
      viewAll: "View all",
      emptyPayments: "No payments received yet",
      emptySettlements: "No settlement history yet",
    },
    settlementControl: {
      title: "Pending Settlement",
      availableForTransfer: "Available for bank transfer",
      frozenMessage: "Settlements are frozen. Complete KYC to unlock bank transfers.",
      processing: "Processing...",
      settleToBank: "Settle to Bank",
      kycRequired: "KYC Required",
    },
    settlementItem: {
      instant: "INSTANT",
      accountPrefix: "A/C",
      feePrefix: "Fee",
    },
    settlementStatusCard: {
      title: "Payout Status",
      paused: "Paused",
      active: "Active",
      nextScheduledPayout: "Next Scheduled Payout",
      blockedMessagePrefix: "Your KYC is currently",
      blockedMessageSuffix: ". Complete verification to resume automated daily settlements.",
      pending: "PENDING",
    },
    statCard: {
      noComparisonData: "No comparison data",
    },
    statsCards: {
      todayCollection: "Today's Collection",
      comparedYesterday: "Compared to yesterday",
      monthlyCollection: "Monthly Collection",
      comparedLastMonth: "Compared to last month",
    },
    transactionItem: {
      directPayment: "Direct Payment",
    },
    viewMoreButton: {
      viewAllPrefix: "View All",
      recordsSuffix: "Records",
    },
  },
  publicComponents: {
    ctaSection: {
      heading: "Ready to get started?",
      subheading: "Join millions of users who trust PayWallet for their daily transactions",
      badge: "Start SwiftPay now",
      primaryCta: "Start SwiftPay Now",
      downloadAppNow: "Download App Now",
      learnMore: "Learn More",
      statsCard: {
        instantSettlementTitle: "1% Instant Settlement",
        instantSettlementDesc: "Transparent fee structure for faster merchant payouts.",
        insightsTitle: "Weekly + Monthly Insights",
        insightsDesc: "Monitor growth and cashflow with clear business snapshots.",
        securityTitle: "Bank-Grade Security",
        securityDesc: "Protected transactions with trusted end-to-end safeguards.",
      },
    },
    featuresSection: {
      badge: "SwiftPay Product Edge",
      featureTags: ["Instant", "Everyday", "Shared", "Secure", "Fast", "Smart"],
      brandTag: "SwiftPay",
      heading: "Everything in one wallet",
      subheading: "Powerful features to manage your money, grow your business, and stay secure",
      features: [
        {
          title: "Instant Transfers",
          description: "Send money to anyone instantly with just their phone number or email",
          color: "bg-blue-50 text-blue-600",
        },
        {
          title: "Bill Payments",
          description: "Pay all your bills, recharge mobile, and manage subscriptions in one place",
          color: "bg-cyan-50 text-cyan-600",
        },
        {
          title: "Merchant Solutions",
          description: "Accept payments from customers with QR codes and payment links",
          color: "bg-teal-50 text-teal-600",
        },
        {
          title: "Bank-Level Security",
          description: "Your money and data protected with military-grade encryption",
          color: "bg-blue-50 text-blue-600",
        },
        {
          title: "Lightning Fast",
          description: "Transactions complete in seconds, not hours or days",
          color: "bg-cyan-50 text-cyan-600",
        },
        {
          title: "Smart Analytics",
          description: "Track spending, income, and get insights to save more money",
          color: "bg-teal-50 text-teal-600",
        },
      ],
    },
    productStoriesSection: {
      badge: "SwiftPay Journeys",
      heading: "Everything users and merchants need, in one flow",
      subheading:
        "Explore how SwiftPay handles personal transfers, group splits, merchant growth tracking, and low-fee instant settlements.",
      cards: [
        {
          title: "Send money instantly to friends",
          description:
            "From coffee splits to rent transfers, SwiftPay sends money in seconds with secure confirmations and full history tracking.",
          media: "/animated/send-money.svg",
          points: ["Real-time transfer confirmation", "One-tap repeat payments", "Smart activity timeline"],
          tint: "from-blue-500/15 to-cyan-500/15",
        },
        {
          title: "Split bills without confusion",
          description:
            "Create split groups, assign equal or custom shares, and track who has paid so every group expense closes cleanly.",
          media: "/animated/split-bill.svg",
          points: ["Equal and custom split modes", "Pending payment reminders", "Auto-updated settlement status"],
          tint: "from-cyan-500/15 to-teal-500/15",
        },
        {
          title: "Merchant growth visibility, weekly and monthly",
          description:
            "Track collection trends, repeat customer behavior, and weekly/monthly summaries to make better cashflow decisions.",
          media: "/animated/merchant-growth.svg",
          points: ["Weekly collection trend cards", "Monthly performance snapshots", "Repeat-customer signal tracking"],
          tint: "from-emerald-500/15 to-teal-500/15",
        },
        {
          title: "Instant settlement at just 1%",
          description:
            "Settle to bank quickly with transparent pricing. Instant settlement carries only 1% fee, engineered to stay among the lowest in market.",
          media: "/animated/instant-settlement.svg",
          points: ["Instant bank transfer option", "Clear fee visibility before payout", "Reliable daily settlement control"],
          tint: "from-blue-600/15 to-indigo-500/15",
          badge: "1% instant settlement",
        },
      ],
    },
    heroSection: {
      trustedBy: "Trusted by 5M+ users",
      headingPrefix: "Pay, Send & Manage Money",
      headingAccent: "Effortlessly",
      description:
        "The complete digital wallet for all your financial needs. Pay bills, transfer money, accept payments, and grow your business with zero hassle.",
      registerUser: "Register as User",
      registerMerchant: "Register as Merchant",
      goToDashboard: "Go to Dashboard",
      alreadyHaveAccount: "Already have an account? Login",
      availableBalance: "Available Balance",
      actions: {
        sendMoney: "Send Money",
        addMoney: "Add Money",
        payBills: "Pay Bills",
        recharge: "Recharge",
      },
      paymentSent: "Payment Sent",
      minsAgo: "2 mins ago",
      security: "Security",
      bankGrade: "Bank-grade",
    },
    publicFooter: {
      brand: "SwiftPay",
      description: "Simplifying digital finance for everyone, everywhere. Secure, fast, and transparent.",
      company: "Company",
      about: "About",
      careers: "Careers",
      contact: "Contact",
      legal: "Legal",
      privacy: "Privacy",
      terms: "Terms",
      cookies: "Cookies",
      newsletterTitle: "Join our newsletter",
      newsletterSubtitle: "Get the latest updates on new features and crypto tips.",
      emailPlaceholder: "Email address",
      subscribe: "Subscribe",
      copyright: "© 2025 SwiftPay Inc. All rights reserved. Your trusted digital wallet.",
    },
    statsSection: {
      stats: [
        { end: "5", suffix: "M+", label: "Active Users" },
        { end: "2", suffix: "B+", label: "Transactions", prefix: "$" },
        { end: "150", suffix: "+", label: "Countries" },
        { end: "99.9", suffix: "%", label: "Uptime", decimals: 1 },
      ],
    },
  },
  userComponents: {
    addMoneyModal: {
      title: "Add Money to Wallet",
      amountLabel: "Amount",
      amountPlaceholder: "0.00",
      processing: "Processing...",
      proceedToAdd: "Proceed to Add",
    },
    balanceOverview: {
      walletBalance: "Wallet Balance",
      add: "Add",
      send: "Send",
      withdraw: "Withdraw",
      split: "Split",
      defaultBalance: "0.00",
    },
    sendMoneyModal: {
      title: "Send Money",
      recipientMobile: "Recipient Mobile",
      mobilePlaceholder: "Enter 10 digit number",
      verifiedRecipient: "Verified Recipient",
      noRecipientFound: "No contact available for this mobile number.",
      amountLabel: "Amount",
      amountPlaceholder: "0.00",
      secureMpin: "Secure MPIN",
      mpinPlaceholder: "\u2022\u2022\u2022\u2022",
      transferring: "Transferring...",
      fillAllFields: "Please fill all fields",
    },
    spendingInsightCard: {
      monthlySpending: "Monthly Spending",
      defaultAmount: "0.00",
      noSpending: "No spending yet this month",
      startUsingWallet: "Start using your wallet to track expenses and insights",
      vsLastMonth: "vs last month",
    },
    transactionItem: {
      pending: "Pending",
      failed: "Failed",
    },
    withdrawMoneyModal: {
      title: "Withdraw to Bank",
      description: "Transfer funds from your wallet back to your linked bank account.",
      destinationAccount: "Destination Account",
      amountToWithdraw: "Amount to Withdraw",
      amountPlaceholder: "0.00",
      enterMpin: "Enter 4-Digit MPIN",
      mpinPlaceholder: "\u2022\u2022\u2022\u2022",
      processingWithdrawal: "Processing Withdrawal...",
      confirmWithdraw: "Confirm & Withdraw",
    },
  },
  pages: {
    loginPage: {
      title: "Welcome Back",
      subtitle: "Sign in to your SwiftPay account",
      emailPlaceholder: "Email address",
      passwordPlaceholder: "Password",
      invalidCredentials: "Invalid email or password",
      rememberMe: "Remember me",
      forgotPassword: "Forgot password?",
      signingIn: "Signing in...",
      signIn: "Sign In",
      noAccount: "Don't have an account?",
      registerUser: "Register as User",
      registerMerchant: "Register as Merchant",
      backToHome: "Back to Home",
    },
    registerUserPage: {
      title: "Create Account",
      subtitle: "Join SwiftPay as a user",
      fullNamePlaceholder: "Full Name",
      emailPlaceholder: "Email address",
      mobilePlaceholder: "Mobile number",
      passwordPlaceholder: "Password",
      createAccount: "Create Account",
      alreadyHaveAccount: "Already have an account?",
      signIn: "Sign In",
      backToHome: "Back to Home",
    },
    registerMerchantPage: {
      title: "Merchant Account",
      subtitle: "Start accepting payments today",
      fullNamePlaceholder: "Full Name",
      emailPlaceholder: "Email address",
      mobilePlaceholder: "Mobile number",
      passwordPlaceholder: "Password",
      businessNamePlaceholder: "Business Name",
      categoryPlaceholder: "Select Business Category",
      successMessage: "Merchant account created successfully! Redirecting...",
      onboarding: "Onboarding...",
      startAccepting: "Start Accepting Payments",
      existingPartner: "Existing partner?",
      signIn: "Sign In",
      backToPortal: "Back to Portal",
    },
    userDashboard: {
      loading: "Loading Dashboard...",
      error: "Error loading dashboard",
      recentTransactions: "Recent Transactions",
      viewAll: "View all",
    },
    transactionsPage: {
      backToDashboard: "Back to Dashboard",
      title: "Transactions",
      subtitle: "View and manage your digital wallet activity.",
      fetchingHistory: "Fetching history...",
      loadError: "We couldn't load your activity",
      tryAgain: "Try Again",
      recentActivity: "Recent Activity",
      itemsFoundSuffix: "items found",
      noTransactions: "No transactions found in this period.",
      viewMore: "View more activity",
      endOfHistory: "Securely Encrypted End of History",
    },
    kycPage: {
      loading: "Loading KYC status...",
      title: "KYC Verification",
      selectFileAlert: "Please select a file",
      underReviewTitle: "KYC Under Review",
      underReviewDesc: "Your documents are being reviewed.",
      approvedTitle: "KYC Approved",
      approvedDesc: "Your KYC is verified successfully.",
      rejectedTitle: "KYC Rejected",
      viewUploadedDoc: "View Uploaded Document",
      close: "Close",
      uploadTitle: "Upload KYC Document",
      uploadButton: "Upload",
      previewTitle: "KYC Document",
    },
    adminKycPage: {
      downloadingSecureDocument: "Downloading secure document...",
      accessDenied: "Access Denied: Could not retrieve document.",
      rejectReasonRequired: "Please provide a rejection reason",
      rejectSuccess: "KYC Rejected successfully",
      rejectFailed: "Failed to process rejection",
      approveSuccess: "KYC Approved. User now has full access.",
      approveFailed: "Approval failed.",
      failedLoad: "Failed to load KYC data",
      tryAgain: "Try Again",
      title: "Compliance Queue",
      pendingSuffix: "PENDING",
      subtitle: "Verify identity documents to enable wallet features for merchants and users.",
      searchPlaceholder: "Search by name or ID...",
      noPendingTitle: "No pending requests",
      noResults: "No results match your search criteria.",
      queueEmpty: "The verification queue is currently empty.",
      processing: "Processing Transaction...",
    },
    merchantDashboard: {
      loading: "Loading Merchant Portal...",
    },
    merchantTransactionsPage: {
      title: "Transaction History",
      subtitle: "View and export your customer payments",
      exportCsv: "Export CSV",
      allTransactions: "All Transactions",
      updating: "Updating...",
      dateTime: "Date & Time",
      customerId: "Customer / ID",
      method: "Method",
      amount: "Amount",
      status: "Status",
      direct: "Direct",
      showingPage: "Showing Page",
      of: "of",
    },
    settlementHistoryPage: {
      title: "Settlements",
      subtitle: "Track funds transferred to your bank",
      statement: "Statement",
      transferLogs: "Transfer Logs",
      settledDate: "Settled Date",
      destinationBank: "Destination Bank",
      type: "Type",
      amount: "Amount",
      fee: "Fee",
      status: "Status",
      accountPrefix: "A/C ..",
      instant: "INSTANT",
      standard: "Standard",
      success: "SUCCESS",
      records: "Records",
      prev: "Prev",
      next: "Next",
    },
    receivePaymentsPage: {
      title: "Receive Payments",
      merchantName: "Sharma Stores",
      scanToPay: "Scan to pay instantly",
      walletIdLabel: "Wallet ID",
      copiedTitle: "Copied!",
      copiedDesc: "Wallet ID copied to clipboard",
      shareTitle: "Pay to Sharma Stores",
      shareTextPrefix: "Pay to",
      share: "Share",
      download: "Download",
      howToTitle: "How to receive payments",
      step1: "Customer opens their FinPay app",
      step2: "They scan this QR code or enter your Wallet ID",
      step3: "Payment is credited instantly to your wallet",
    },
    sendMoneyPage: {
      title: "Send Money",
      sendTo: "Send to",
      receiverPlaceholder: "Mobile number or email",
      receiverHint: "Enter mobile number or registered email",
      amountLabel: "Amount",
      amountPlaceholder: "0",
      availableBalance: "Available Balance",
      continue: "Continue",
      enterMpin: "Enter MPIN to Send",
      transferSuccess: "Transfer Successful!",
      transferFailed: "Transfer Failed",
      transferSuccessMessagePrefix: "Money sent to",
      transferSuccessMessageSuffix: "successfully.",
      transferFailedMessage: "Unable to process transaction. Please try again.",
    },
    settlementPage: {
      title: "Settlement",
      availableForSettlement: "Available for Settlement",
      minSettlement: "Minimum settlement: ",
      selectBank: "Select Bank Account",
      settlementAmount: "Settlement Amount",
      settleAll: "Settle All",
      initiateSettlement: "Initiate Settlement",
      recentSettlements: "Recent Settlements",
      completed: "Completed",
      enterMpin: "Enter MPIN to Settle",
      successTitle: "Settlement Initiated!",
      failedTitle: "Settlement Failed",
      successMessagePrefix: " will be credited to ",
      successMessageSuffix: " within 24 hours.",
      failedMessage: "Unable to process settlement. Please contact support.",
    },
    notFoundPage: {
      notFoundCode: "404",
      description: "Oops! The page you're looking for doesn't exist.",
      backToHome: "Back to Home",
      consolePrefix: "404 Error: User attempted to access non-existent route:",
    },
    unauthorizedPage: {
      title: "Unauthorized Access",
      description: "You don't have permission to view this page.",
      goToHome: "Go to Home",
    },
    highValueMerchantSummaryPage: {
      title: "High Value Merchants",
      subtitle: "Set threshold and search merchants by name.",
      minAmountPlaceholder: "Min amount (INR)",
      apply: "Apply",
      downloadXlsx: "Download .xlsx",
      downloading: "Downloading...",
      downloadStarted: "Download started",
      downloadFailed: "Failed to download .xlsx file",
      summary: "Summary",
      searchPlaceholder: "Search merchant name...",
      showing: "Showing",
      offset: "Offset",
      failedLoad: "Failed to load merchants",
      noMerchants: "No merchants found.",
      business: "Business",
      code: "Code",
      category: "Category",
      highTxns: "High Txns",
      totalAmount: "Total Amount",
      distinctPayers: "Distinct Payers",
      action: "Action",
      viewMore: "View More",
      offsetLabel: "Offset:",
      prev: "Prev",
      next: "Next",
    },
    highValueMerchantTransactionsPage: {
      title: "Merchant Transactions",
      subtitlePrefix: "High-value transactions (minAmount:",
      subtitleSuffix: ")",
      back: "Back",
      downloadXlsx: "Download .xlsx",
      downloading: "Downloading...",
      downloadStarted: "Download started",
      downloadFailed: "Failed to download .xlsx file",
      merchantPrefix: "Merchant #",
      codePrefix: "Code:",
      categoryPrefix: "Category:",
      failedLoad: "Failed to load transactions",
      noTransactions: "No transactions found.",
      tx: "Tx",
      reference: "Reference",
      payer: "Payer",
      amount: "Amount",
      status: "Status",
      mode: "Mode",
      type: "Type",
      created: "Created",
      offset: "Offset:",
      prev: "Prev",
      next: "Next",
      statusSuccess: "SUCCESS",
      statusFailed: "FAILED",
      statusPending: "PENDING",
    },
  },
  splits: {
    common: {
      rupee: "\u20B9",
      dash: "\u2014",
    },
    widget: {
      title: "Splits",
      youOwe: "You owe:",
      createSplit: "Create Split",
      tabOwe: "I Owe",
      tabCreated: "Created",
      loading: "Loading...",
      noPendingSplits: "No pending splits.",
      noActiveCreatedSplits: "No active created splits.",
      noNote: "No note",
      pay: "Pay",
      paidSuffix: "paid",
      completedStatuses: ["COMPLETE", "COMPLETED", "CLOSED", "SETTLED", "PAID"],
    },
    createModal: {
      title: "Create Split",
      participantsLabel: "participant",
      participantsLabelPlural: "participants",
      submit: "Create Split",
    },
    createSections: {
      splitTypeLabel: "Split type",
      equal: "Equal",
      custom: "Custom",
      equalHint: "Amount must divide equally (paise precision).",
      customHint: "Enter exact share per participant. Sum must match total.",
      participantMobileLabel: "Participant mobile",
      mobilePlaceholder: "10 digit mobile",
      add: "Add",
      foundUser: "Found user",
      totalAmountLabel: "Total amount",
      amountPlaceholder: "0.00",
      eachPrefix: "Each:",
      notDivisiblePrefix: "Not divisible among",
      noteLabel: "Note (optional)",
      notePlaceholder: "Dinner / Trip / Rent...",
      participants: "Participants",
      entered: "Entered:",
      remaining: "Remaining:",
      noParticipants: "No participants added yet.",
      searchHint: "Search by mobile number above.",
      participantHeader: "Participant",
      shareHeader: "Share",
      shareInputPlaceholder: "0.00",
      shareHintLeft: "Enter amounts with max 2 decimals.",
      shareHintRight: "Sum must equal total.",
    },
    payModal: {
      title: "Pay your share",
      splitLabel: "Split",
      enterMpinLabel: "Enter MPIN",
      mpinPlaceholder: "\u2022\u2022\u2022\u2022",
      payNow: "Pay now",
    },
    toasts: {
      noUserFound: "No user found for this mobile",
      alreadyAdded: "Already added",
      addParticipant: "Add at least 1 participant",
      enterValidAmount: "Enter a valid amount",
      amountMaxTwoDecimals: "Amount must have at most 2 decimal places",
      equalAmountDivisibility: "Amount must be divisible equally among participants (paise precision).",
      invalidCustomSplit: "Invalid custom split",
    },
    validation: {
      enterAllShares: "Enter share for all participants",
      sharesMaxTwoDecimals: "Shares must have at most 2 decimals",
      shareMustBePositive: "Each share must be > 0",
      invalidShareAmounts: "Invalid share amount(s)",
      customShareTotalMismatchPrefix: "Custom shares must sum to total. Remaining:",
    },
  },
};
