import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'

import { registerSW } from "virtual:pwa-register"; // this also comes from the vite-plugin only.
import { toast } from 'sonner';

/**
 * The service worker that is generated by the workbox is getting registered now.
 * registerSW returns a function updateSW to manually trigger updates.
 * 
 * without immediate: true, the service worker might register after the page finishes loading.
 *  
 * updateSW(true) : Activate the new service worker immediately and reload the page.
 */
const updateSW = registerSW({
  immediate: true, // Register the service worker immediately when the app loads.

  // A new version of the app is available
  onNeedRefresh() {
    toast("A new app version is available.", {
      action: {
        label: "Update", // simply the text on the button.
        onClick: () => updateSW(true),
      },
    });
  },
  // App is finished caching and ready to work offline
  onOfflineReady() {
    toast.success("SwiftPay is ready to work offline.");
  },
});


createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
