spring.application.name=PaytmClone

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/paytmCloneDb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=mysql123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



app.superadmin.email=superadmin@payflow.com
app.superadmin.password=ChangeMe@123
